title: Multi-Modal Speech Recognition, Separation and Diarization, Everything Streaming All at Once
description: Streaming multi-talker ASR and Diarization simultaneously using multi-channel audio-visual information.  
remote_theme: pages-themes/primer@v0.2.0
plugins:
- jekyll-remote-theme
